import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Adds the tables for the new `liveEmbed` block on `projects.execution`
 * (`src/blocks/live-embed.ts`) — live and draft-version, same pair as every
 * other block on that field. Hand-written rather than generated by `payload
 * migrate:create`, same reason as `20260902_120032_add_project_year_end` and
 * `20260918_120000_add_icon_grid_variant`: no live database to diff against
 * from here. Modelled directly on `projects_blocks_prose` in
 * `20260815_181959_cms_schema` — the simplest existing block, no upload
 * relations of its own — with `url`, `height` and the locale columns
 * (`eyebrow`, `heading`, `fallback_label`) added, and `settings_background`
 * / `settings_spacing` copied from `projects_blocks_media`. None of the
 * columns are `NOT NULL`: neither are `client` or `year` on `projects`
 * itself, even though both are `required` in the Payload config — Payload
 * enforces `required` at the application layer, not with a DB constraint,
 * so this migration doesn't add one either.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_projects_blocks_live_embed_settings_background" AS ENUM('paper', 'sumi', 'accent');
  CREATE TYPE "public"."enum_projects_blocks_live_embed_settings_spacing" AS ENUM('compact', 'normal', 'wide');
  CREATE TYPE "public"."enum__projects_v_blocks_live_embed_settings_background" AS ENUM('paper', 'sumi', 'accent');
  CREATE TYPE "public"."enum__projects_v_blocks_live_embed_settings_spacing" AS ENUM('compact', 'normal', 'wide');

  CREATE TABLE "projects_blocks_live_embed" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"url" varchar,
  	"height" numeric DEFAULT 640,
  	"settings_background" "enum_projects_blocks_live_embed_settings_background" DEFAULT 'paper',
  	"settings_spacing" "enum_projects_blocks_live_embed_settings_spacing" DEFAULT 'normal',
  	"settings_animate" boolean DEFAULT true,
  	"block_name" varchar
  );

  CREATE TABLE "projects_blocks_live_embed_locales" (
  	"eyebrow" varchar,
  	"heading" varchar,
  	"fallback_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "_projects_v_blocks_live_embed" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"url" varchar,
  	"height" numeric DEFAULT 640,
  	"settings_background" "enum__projects_v_blocks_live_embed_settings_background" DEFAULT 'paper',
  	"settings_spacing" "enum__projects_v_blocks_live_embed_settings_spacing" DEFAULT 'normal',
  	"settings_animate" boolean DEFAULT true,
  	"_uuid" varchar,
  	"block_name" varchar
  );

  CREATE TABLE "_projects_v_blocks_live_embed_locales" (
  	"eyebrow" varchar,
  	"heading" varchar,
  	"fallback_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  ALTER TABLE "projects_blocks_live_embed" ADD CONSTRAINT "projects_blocks_live_embed_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "projects_blocks_live_embed_locales" ADD CONSTRAINT "projects_blocks_live_embed_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."projects_blocks_live_embed"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_projects_v_blocks_live_embed" ADD CONSTRAINT "_projects_v_blocks_live_embed_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_projects_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_projects_v_blocks_live_embed_locales" ADD CONSTRAINT "_projects_v_blocks_live_embed_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_projects_v_blocks_live_embed"("id") ON DELETE cascade ON UPDATE no action;

  CREATE INDEX "projects_blocks_live_embed_order_idx" ON "projects_blocks_live_embed" USING btree ("_order");
  CREATE INDEX "projects_blocks_live_embed_parent_id_idx" ON "projects_blocks_live_embed" USING btree ("_parent_id");
  CREATE INDEX "projects_blocks_live_embed_path_idx" ON "projects_blocks_live_embed" USING btree ("_path");
  CREATE UNIQUE INDEX "projects_blocks_live_embed_locales_locale_parent_id_unique" ON "projects_blocks_live_embed_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_projects_v_blocks_live_embed_order_idx" ON "_projects_v_blocks_live_embed" USING btree ("_order");
  CREATE INDEX "_projects_v_blocks_live_embed_parent_id_idx" ON "_projects_v_blocks_live_embed" USING btree ("_parent_id");
  CREATE INDEX "_projects_v_blocks_live_embed_path_idx" ON "_projects_v_blocks_live_embed" USING btree ("_path");
  CREATE UNIQUE INDEX "_projects_v_blocks_live_embed_locales_locale_parent_id_unique" ON "_projects_v_blocks_live_embed_locales" USING btree ("_locale","_parent_id");

  ALTER TABLE "projects_blocks_live_embed" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "projects_blocks_live_embed_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_projects_v_blocks_live_embed" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_projects_v_blocks_live_embed_locales" DISABLE ROW LEVEL SECURITY;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "projects_blocks_live_embed" CASCADE;
  DROP TABLE "projects_blocks_live_embed_locales" CASCADE;
  DROP TABLE "_projects_v_blocks_live_embed" CASCADE;
  DROP TABLE "_projects_v_blocks_live_embed_locales" CASCADE;
  DROP TYPE "public"."enum_projects_blocks_live_embed_settings_background";
  DROP TYPE "public"."enum_projects_blocks_live_embed_settings_spacing";
  DROP TYPE "public"."enum__projects_v_blocks_live_embed_settings_background";
  DROP TYPE "public"."enum__projects_v_blocks_live_embed_settings_spacing";`)
}
