import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Auto-generated by `payload migrate:create`, with one manual trim: the
 * generator also produced `ALTER TYPE ... ADD VALUE 'gallery'` statements for
 * the media block's variant enum, because the hand-written
 * `20260824_170500_add_gallery_variant` migration has no drizzle snapshot of
 * its own — so as far as the generator's diff was concerned, `'gallery'`
 * still needed adding. It's already live from that earlier migration, so
 * re-running it here would fail with "already exists" (same failure mode as
 * `20260819_171003`, this time self-inflicted). Removed those four `ALTER
 * TYPE` lines and their mirror in `down()`; everything else is untouched
 * generator output for the new `bio` block.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_bio_image_position" AS ENUM('right', 'left');
  CREATE TYPE "public"."enum_pages_blocks_bio_settings_background" AS ENUM('paper', 'sumi', 'accent');
  CREATE TYPE "public"."enum_pages_blocks_bio_settings_spacing" AS ENUM('compact', 'normal', 'wide');
  CREATE TYPE "public"."enum__pages_v_blocks_bio_image_position" AS ENUM('right', 'left');
  CREATE TYPE "public"."enum__pages_v_blocks_bio_settings_background" AS ENUM('paper', 'sumi', 'accent');
  CREATE TYPE "public"."enum__pages_v_blocks_bio_settings_spacing" AS ENUM('compact', 'normal', 'wide');
  CREATE TABLE "pages_blocks_bio_links" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"label" varchar,
  	"url" varchar
  );
  
  CREATE TABLE "pages_blocks_bio" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"photo_id" integer,
  	"image_position" "enum_pages_blocks_bio_image_position" DEFAULT 'right',
  	"settings_background" "enum_pages_blocks_bio_settings_background" DEFAULT 'paper',
  	"settings_spacing" "enum_pages_blocks_bio_settings_spacing" DEFAULT 'normal',
  	"settings_animate" boolean DEFAULT true,
  	"block_name" varchar
  );
  
  CREATE TABLE "pages_blocks_bio_locales" (
  	"eyebrow" varchar,
  	"heading" varchar,
  	"body" jsonb,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  
  CREATE TABLE "_pages_v_blocks_bio_links" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"label" varchar,
  	"url" varchar,
  	"_uuid" varchar
  );
  
  CREATE TABLE "_pages_v_blocks_bio" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"photo_id" integer,
  	"image_position" "enum__pages_v_blocks_bio_image_position" DEFAULT 'right',
  	"settings_background" "enum__pages_v_blocks_bio_settings_background" DEFAULT 'paper',
  	"settings_spacing" "enum__pages_v_blocks_bio_settings_spacing" DEFAULT 'normal',
  	"settings_animate" boolean DEFAULT true,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  
  CREATE TABLE "_pages_v_blocks_bio_locales" (
  	"eyebrow" varchar,
  	"heading" varchar,
  	"body" jsonb,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  ALTER TABLE "pages_blocks_bio_links" ADD CONSTRAINT "pages_blocks_bio_links_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_bio"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "pages_blocks_bio" ADD CONSTRAINT "pages_blocks_bio_photo_id_media_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_bio" ADD CONSTRAINT "pages_blocks_bio_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "pages_blocks_bio_locales" ADD CONSTRAINT "pages_blocks_bio_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_bio"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_bio_links" ADD CONSTRAINT "_pages_v_blocks_bio_links_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_bio"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_bio" ADD CONSTRAINT "_pages_v_blocks_bio_photo_id_media_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_bio" ADD CONSTRAINT "_pages_v_blocks_bio_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_bio_locales" ADD CONSTRAINT "_pages_v_blocks_bio_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_bio"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "pages_blocks_bio_links_order_idx" ON "pages_blocks_bio_links" USING btree ("_order");
  CREATE INDEX "pages_blocks_bio_links_parent_id_idx" ON "pages_blocks_bio_links" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_bio_order_idx" ON "pages_blocks_bio" USING btree ("_order");
  CREATE INDEX "pages_blocks_bio_parent_id_idx" ON "pages_blocks_bio" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_bio_path_idx" ON "pages_blocks_bio" USING btree ("_path");
  CREATE INDEX "pages_blocks_bio_photo_idx" ON "pages_blocks_bio" USING btree ("photo_id");
  CREATE UNIQUE INDEX "pages_blocks_bio_locales_locale_parent_id_unique" ON "pages_blocks_bio_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_pages_v_blocks_bio_links_order_idx" ON "_pages_v_blocks_bio_links" USING btree ("_order");
  CREATE INDEX "_pages_v_blocks_bio_links_parent_id_idx" ON "_pages_v_blocks_bio_links" USING btree ("_parent_id");
  CREATE INDEX "_pages_v_blocks_bio_order_idx" ON "_pages_v_blocks_bio" USING btree ("_order");
  CREATE INDEX "_pages_v_blocks_bio_parent_id_idx" ON "_pages_v_blocks_bio" USING btree ("_parent_id");
  CREATE INDEX "_pages_v_blocks_bio_path_idx" ON "_pages_v_blocks_bio" USING btree ("_path");
  CREATE INDEX "_pages_v_blocks_bio_photo_idx" ON "_pages_v_blocks_bio" USING btree ("photo_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_bio_locales_locale_parent_id_unique" ON "_pages_v_blocks_bio_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "pages_blocks_bio_links" CASCADE;
  DROP TABLE "pages_blocks_bio" CASCADE;
  DROP TABLE "pages_blocks_bio_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_bio_links" CASCADE;
  DROP TABLE "_pages_v_blocks_bio" CASCADE;
  DROP TABLE "_pages_v_blocks_bio_locales" CASCADE;
  DROP TYPE "public"."enum_pages_blocks_bio_image_position";
  DROP TYPE "public"."enum_pages_blocks_bio_settings_background";
  DROP TYPE "public"."enum_pages_blocks_bio_settings_spacing";
  DROP TYPE "public"."enum__pages_v_blocks_bio_image_position";
  DROP TYPE "public"."enum__pages_v_blocks_bio_settings_background";
  DROP TYPE "public"."enum__pages_v_blocks_bio_settings_spacing";`)
}
