import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Adds the optional `yearEnd` field to `projects`, on both the live table and
 * its draft-version counterpart — `year_end` / `version_year_end`, `numeric`
 * to match `year` / `version_year` right next to it. Hand-written rather than
 * generated by `payload migrate:create`: a plain column addition, same as
 * `20260824_170500_add_gallery_variant`.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "year_end" numeric;
  ALTER TABLE "_projects_v" ADD COLUMN IF NOT EXISTS "version_year_end" numeric;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "projects" DROP COLUMN IF EXISTS "year_end";
  ALTER TABLE "_projects_v" DROP COLUMN IF EXISTS "version_year_end";`)
}
